### PR TITLE
feat: add feature descriptions for text features

### PR DESCRIPTION
**Pull request by sarakolding**
- [x] I have battle-tested on Overtaci (RMAPPS1279)

added feature descriptions for text specs

### CODE REVIEW

**Review by HLasse — APPROVED** [review]
LGTM!

**Comment by HLasse** [comment]
Should probably also append the spec.feature name to the feature_name if multiple sfis are used

**Comment by sarakolding** [comment]
I don't think I understand what you mean 😅

**Comment by HLasse** [comment]
Sorry, that was also a very short comment based on a stray thought ;) I'll add a comment in the code instead

**Comment by HLasse** [comment]
Feel free to merge once mypy passes

**Pull request merged**
