### PR TITLE
feat: added post-processing functionality

### PR DESCRIPTION
**Pull request by HLasse**
- [ ] I have battle-tested on Overtaci (RMAPPS1279)
- [ ] I have assigned ranges (e.g. `>=0.1, <0.2`) to all new dependencies (allows dependabot to keep dependency ranges wide for better compatability)

## Notes for reviewers
Adds the opportunity for doing basic post-processing following feature creation. See [schz-bp-feature-generation](https://github.com/Aarhus-Psychiatry-Research/schz-bp-feature-generation/blob/0d31ba1141a0110cc0bc942dfae12db9c2cab007/application/main.py#L61) for an example.

Remains to be battle tested

### CODE REVIEW

**Comment by MartinBernstorff** [comment]
Love this Lasse! Great implementation, looks super clean.

Unsure if this should be in feature-generation or model-training though! I.e. many of the things you've implemented here are already handled by the pre-processing steps in `psycop-model-training`. Let's talk about it, so we don't have 2 week stale PRs hanging around ;-)

**Comment by HLasse** [comment]
Yep, realised later that much of it is already there. Main motivation for having it outside `psycop-model-training` would be to make it easier to migrate to other training scripts (e.g. from vdS). But yep, let's talk tomorrow ;)

**Comment by HLasse** [comment]
After discussion:
- Consider refactoring the relevant row/col filter from timeseriesflattener to not require an entire config, but only a preprocessing config and write an interface for them so they can be used in the same way. 
- Add missing functionality there (e.g. age max)

**Comment by MartinBernstorff** [comment]
@HLasse, are you OK with closing this? :-)

**Comment by HLasse** [comment]
Yes, kill it

**Pull request closed without merging**
